# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import hikari
from google.adk.agents import Agent
from google.adk.tools.agent_tool import AgentTool
from google.adk.runners import Runner
from google.adk.tools import google_search
from google.genai.types import Content, GenerateContentConfig, SafetySetting, HarmCategory, HarmBlockThreshold

from .common import session_service, ensure_session_exists, message_to_content, load_prompt, USER
from config import (
    ROOT_AGENT_NAME,
    ROOT_AGENT_MODEL,
    ROOT_AGENT_DESCRIPTION, SEARCH_AGENT_DESCRIPTION, SEARCH_AGENT_NAME,
)

from .document_reader_agent import document_reader


search_agent = Agent(
    model='gemini-2.0-flash',
    name=SEARCH_AGENT_NAME,
    description=SEARCH_AGENT_DESCRIPTION,
    instruction="""
    You're a specialist in Google Search and you can look up any information needed.
    """,
    tools=[google_search],
)


root_agent = Agent(
    name=ROOT_AGENT_NAME,
    model=ROOT_AGENT_MODEL,
    description=ROOT_AGENT_DESCRIPTION,
    instruction=(
        load_prompt('root_agent')
    ),
    tools=[AgentTool(search_agent), AgentTool(document_reader)],
    generate_content_config=GenerateContentConfig(
        temperature=0.1, # More deterministic output
        max_output_tokens=600,
        safety_settings=[
            SafetySetting(
                category=HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            )
        ]
    )
)

async def reply_to_message(message: hikari.Message, channel_id: int) -> Content:
    """
    This is the main function to generate answers to user queries. Receives the incoming message from the user and
    channel_id. The channel_id is used as a session id to keep track of the conversation.

    Returns:
        A Content object with the final answer generated by the root_app.
    """
    from app import root_app

    runner = Runner(
        app=root_app,
        session_service=session_service,
    )

    await ensure_session_exists(channel_id)

    new_message = message_to_content(message)
    for event in runner.run(user_id=USER, session_id=str(channel_id), new_message=new_message):
        if event.is_final_response():
            return event.content
    raise RuntimeError